from .conv1d import get_op_and_shape
from .conv2d import get_op_and_shape
from .conv3d import get_op_and_shape
from .global_avg_pool1d import get_op_and_shape
from .global_avg_pool2d import get_op_and_shape
from .global_avg_pool3d import get_op_and_shape
from .global_max_pool1d import get_op_and_shape
from .global_max_pool2d import get_op_and_shape
from .global_max_pool3d import get_op_and_shape
from .batch_norm1d import get_op_and_shape
from .batch_norm2d import get_op_and_shape
from .batch_norm3d import get_op_and_shape
from .layer_norm1d import get_op_and_shape
from .layer_norm2d import get_op_and_shape
from .layer_norm3d import get_op_and_shape
from .dense import get_op_and_shape
from .avg_pool1d import get_op_and_shape
from .max_pool1d import get_op_and_shape
from .max_pool2d import get_op_and_shape
from .avg_pool2d import get_op_and_shape
from .max_pool3d import get_op_and_shape
from .avg_pool3d import get_op_and_shape
from .flatten import get_op_and_shape
from .softmax import get_op_and_shape
from .relu import get_op_and_shape
from .elu import get_op_and_shape
from .selu import get_op_and_shape
from .sigmoid import get_op_and_shape
from .tanh import get_op_and_shape
from .p_relu import get_op_and_shape
from .leaky_relu import get_op_and_shape
from .relu6 import get_op_and_shape
from .add import get_op_and_shape
from .subtract import get_op_and_shape
from .multiply import get_op_and_shape
from .divide import get_op_and_shape
from .maximum import get_op_and_shape
from .minimum import get_op_and_shape
from .average import get_op_and_shape
from .concatenate import get_op_and_shape
from .rnn import get_op_and_shape
from .gru import get_op_and_shape
from .lstm import get_op_and_shape
from .bi_gru import get_op_and_shape
from .bi_rnn import get_op_and_shape
from .bi_lstm import get_op_and_shape
from .conv2dtranspose import get_op_and_shape
from .conv3dtranspose import get_op_and_shape
from .dropout import get_op_and_shape
from .reshape import get_op_and_shape
from .zero_pad2d import get_op_and_shape
from .transpose import get_op_and_shape
from .reduce_max import get_op_and_shape
from .reduce_mean import get_op_and_shape
from .reduce_sum import get_op_and_shape
from .reduce_prod import get_op_and_shape
from .argmax import get_op_and_shape
from .argmin import get_op_and_shape
from .bias_add import get_op_and_shape
from .cast import get_op_and_shape
from .ceil import get_op_and_shape
from .floor import get_op_and_shape
from .exp import get_op_and_shape
from .sqrt import get_op_and_shape
from .rsqrt import get_op_and_shape
from .square import get_op_and_shape
from .unsqueeze import get_op_and_shape
from .squeeze import get_op_and_shape
from .compare import get_op_and_shape
from .tile import get_op_and_shape
from .top_k import get_op_and_shape
from .gather import get_op_and_shape
from .resize import get_op_and_shape
from .crop_and_resize import get_op_and_shape
from .slice import get_op_and_shape
from .strided_slice import get_op_and_shape
from .upsample1d import get_op_and_shape
from .upsample2d import get_op_and_shape
from .upsample3d import get_op_and_shape
from .rnn_cell import get_op_and_shape
from .gru_cell import get_op_and_shape
from .lstm_cell import get_op_and_shape
from .lamb import get_op_and_shape
from .repeat import get_op_and_shape
from .gaussian_noise import get_op_and_shape
from .threshold import get_op_and_shape
from .separable_conv2d import get_op_and_shape
from .separable_conv1d import get_op_and_shape
from .depthwise_conv1d import get_op_and_shape
from .depthwise_conv2d import get_op_and_shape
from .embedding import get_op_and_shape
from .shape import get_op_and_shape
